title: Yunna Kim  # You can add your name here

logo: YunnaKim.png # Use a relative path to logo image 

description: Neuropsychiatry in Korean medicine #- where bytes and botany blend for a better world. # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: yunna.anna.kim@khu.ac.kr # Allow visitors to contact you
